const script = document.createElement("script");
script.src = "https://widget.kapa.ai/kapa-widget.bundle.js";
script.async = true;
script.setAttribute("data-website-id", "bb3db8a4-cff5-4a2c-998d-83ebd7170a49");
script.setAttribute("data-project-name", "AssemblyAI");
script.setAttribute("data-project-color", "#2C4BD4");
script.setAttribute("data-project-logo", "/images/logo-blue400x400.jpeg");
script.setAttribute("data-user-analytics-fingerprint-enabled", "true");
script.setAttribute("data-modal-override-open-id-search", "search-bar-entry");
document.head.appendChild(script);
